/*
 * eChallan System
 * ### API Specs For eChallan System ### 1. Generate the new challan. 2. Update the details of existing challan 3. Search the existing challan 4. Generate the demand and bill for the challan amount so that collection can be done in online and offline mode. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.egov.lams.model;



import java.util.ArrayList;
import java.util.List;

import org.egov.common.contract.request.Role;
import org.egov.common.contract.request.User;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * This is acting ID token of the authenticated user on the server. Any value provided by the clients will be ignored and actual user based on authtoken will be used on the server.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-10T16:46:24.044+05:30[Asia/Calcutta]")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class UserInfo extends User {

  //@JsonProperty("tenantId")

  //private String tenantId;

  //@JsonProperty("uuid")

  //private String uuid;

  //@JsonProperty("name")

  //private String name;

  //@JsonProperty("password")

  //private String password;

  //@JsonProperty("idToken")

  //private String idToken;

  //@JsonProperty("mobileNumber")

  //private String mobileNumber;

  //@JsonProperty("emailId")

  //private String emailId;

  //@JsonProperty("primaryrole")

  //private List<Role> primaryrole = new ArrayList<Role>();

  
  @JsonProperty("aadhaarNumber")
  private String aadhaarNumber;
  
  @JsonProperty("pan")
  private String pan;
  
  @JsonProperty("roles")
  private List<Role> roles;
  
  private Boolean active;
  //private Gender gender;
  
  public void addUserDetail(User user){
      this.setId(user.getId());
      this.setUserName(user.getUserName());
      this.setName(user.getName());
      this.setMobileNumber(user.getMobileNumber());
      this.setEmailId(user.getEmailId());
      this.setType(user.getType());
      this.setRoles(user.getRoles());
      this.setTenantId(user.getTenantId());
}

}
